import { Inter } from "next/font/google";
import "../globals.css";
import SidenavDashboard from "../components/dashboard/SideNav";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/Authcontext";
import Navbar from "../components/dashboard/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full flex`}>
        <AuthProvider>
          <SidenavDashboard />
          <div className="w-full">
            <Navbar />
            <div>{children}</div>
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
