import { Inter } from "next/font/google";
import "../globals.css";
import SidenavDashboard from "../components/dashboard/SideNav";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full flex`}>
        <SidenavDashboard />
        <div className="w-full">
          <div className="bg-primary h-16 w-full shadow-md border text-red-500"></div>
          <div>{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
